apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dqyre7npk-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ebf404ab27.mquk.p3.openshiftapps.com/rhtap/rhtap-qe:26d034c0c970b1a14a4e16cb2c4378f9192c2bce@sha256:5bbf749af8d76a6b383c550c7afbfe123ed720557700a2860a024b2f7a326b3d
          name: container-image
